### ISSUE TITLE
Authentication in non-admin account doesn't show the admin username

### ISSUE THREAD

**Issue by BrusAndr** [elementary/pantheon-agent-polkit#14]
The other day, I noticed a strange bug. If there are several users on elementaryOS, then when authenticating the 2nd user, you can use the password from the first one. This doesn't work on the login screen or in terminal, when I running "sudo su", but works when upgraded in AppCenter or when pantheon-files are opened in Administrator mode. Here's a detailed explanation of how it all works:

Test: first account, account type - administrator, exists in sudo group, password - qwerty
Test2: second account, account type - standard, doesn't exists in sudo group, password - 123456

![screenshot from 2017-09-08 14 39 02](https://user-images.githubusercontent.com/29145756/30211436-b24c843c-94a9-11e7-919a-62fe15600c25.png)
![screenshot from 2017-09-08 14 38 49](https://user-images.githubusercontent.com/29145756/30211422-a2f29936-94a9-11e7-9d57-0dd3bba1b340.png)

I can press "unlock", enter the password from the first account "qwerty" **(But, I'm sitting from the second account!?)**, and I'll get more permissions (root).

![screenshot from 2017-09-08 14 40 08](https://user-images.githubusercontent.com/29145756/30211582-4e96a926-94aa-11e7-98ad-4186de1ee2dc.png)
![screenshot from 2017-09-08 14 39 35](https://user-images.githubusercontent.com/29145756/30211586-55d3dba0-94aa-11e7-9a27-11fbc337baa1.png)
![screenshot from 2017-09-08 14 40 37](https://user-images.githubusercontent.com/29145756/30211589-58630efe-94aa-11e7-9a18-3f0289258795.png)

![screenshot from 2017-09-08 14 41 04](https://user-images.githubusercontent.com/29145756/30211756-e9b07748-94aa-11e7-903d-deca98ac1f91.png)
![screenshot from 2017-09-08 14 41 27](https://user-images.githubusercontent.com/29145756/30211761-ec1c4f52-94aa-11e7-8c1c-1264106086db.png)
![screenshot from 2017-09-08 14 41 41](https://user-images.githubusercontent.com/29145756/30211765-ef4a021e-94aa-11e7-8d32-fccfc9dd2013.png)

I ran tests on two PCs: first PC - my main computer, and on second PC, elementaryOS was installed from scratch. On both PCs installed elementaryOS 0.4.1 stable. With all the upgrades. This bug appeared on both machines. This does not give any advantages to attackers, because it still requires a password, but this is an unpleasant problem that should not be.

PC specs:
![2017-09-08 14 52 26](https://user-images.githubusercontent.com/29145756/30212065-f6f13360-94ab-11e7-9eb0-c5ec6545430f.png)
![screenshot from 2017-09-08 14 38 27](https://user-images.githubusercontent.com/29145756/30212014-d3d3a430-94ab-11e7-8a5b-505e2ab6b2b4.png)

**Thanks for attention, I hope this problem will be solved :)**

**Comment by matzipan** [comment]
Thanks for the report! It's being looked into.

**Comment by tintou** [comment]
Thank you for your bug report and the high quality of its description.
Usually, when there are multiple administrators, there is a combobox shown with every administrator to select against which user you want to login.
In this dialog we used to not show the required user when there was only one administrator but that probably because we missed the case when there is one admin and several standard accounts, we need to show that it's the password of `AdminAccountName` that is required when it's not the current one.

**Comment by BrusAndr** [comment]
Hello! I understand that developing elementaryOS is not an easy task, but this bug is already 3 months old and it's still not fixed. I'm writing this message in case you forgot about this bug.

**Comment by matzipan** [comment]
I can assure you nobody has. If you feel like you want to incentivise the developers to tackle this problem, feel free to place a bounty. Or you can try and tackle it yourself and we can help you get started.
