### ISSUE TITLE
Show avatar placeholder in combobox

### ISSUE THREAD

**Issue by danrabbit** [elementary/pantheon-agent-polkit#15]
![screenshot from 2017-12-07 12 50 14](https://user-images.githubusercontent.com/7277719/33738476-380f9e2a-db4e-11e7-8dd3-84bbeabdf832.png)

It looks kinda funny that the entry has an icon but the combobox doesn't. We should probably squeeze an `avatar-default-symbolic` in there for symmetry

**Comment by cassidyjames** [comment]
@danrabbit would the actual avatar be too awkward here?
