### ISSUE TITLE
Unlock Firewall settings button runs a glitched always moving login window

### ISSUE THREAD

**Issue by hawake** [elementary/pantheon-agent-polkit#76]
Hi,
I have found something strange in the Settings Manager -> Security and Privacy window. In particular when I try to unlock firewall settings, the usual login window for root privileges appear but it is constatly moving and refreshing, preventing me to correctly insert the required password.
The following screenshot captured just one frame, but as you can see is reporting an Incorrect permissions error of PolicyKit.

![screenshot_bug_login_window1](https://user-images.githubusercontent.com/673387/56849798-99eb7080-68f9-11e9-8185-82fa2ed6e038.png)

OS: Elementary OS 5.0
Uname: Linux 4.15.0-36-generic elementary/switchboard-plug-security-privacy#39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Language: Italian
Hardware Configuration: Intel Core i5 750 @ 2.67 GHz, 8 GB of RAM and AMD Radeon RX580.

Are there any further information I can report here to be helpful?

Thanks.

**Comment by danirabbit** [comment]
Gonna close this since this is very old and the polkit agent has since been ported to Gtk4 and this looks like maybe a Gtk3 bug with non-wrapping labels
